### ISSUE TITLE
Зачем?

### ISSUE THREAD

**Issue by poststatist** [medium-isp/medium-nic#1]
Забыл о том, что сам писал на хабре про "централизованное всё"?

**Comment by podivilov** [comment]
Запасной вариант необходим. Ты мейнтейнишь репо medium-dns, но вот уже как почти неделя прошла, а результата никакого нет. Тем временем пользователям нужно пользоваться DNS.

**Comment by poststatist** [comment]
Я недопилил, а ты перевел основной DNS в RO

**Comment by podivilov** [comment]
Основной DNS сейчас находится в medium-nic.

**Comment by poststatist** [comment]
А остальные 5 шт?

**Comment by poststatist** [comment]
И реги новых доменов в нем открыты?

**Comment by podivilov** [comment]
Я не нахожу обсуждение аспектов нового NIC целесообразным в пределах данного обсуждения. Всё уже обсуждалось в группе ТГ. Если есть потребность в обсуждении принципов работы нового DNS, то нужно обсуждать это дело с сообществом, а не только со мной. Тикет закрываю.
